version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: absensi_suma
    ports:
      - 8000:80
      - 5173:5173
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    container_name: mysql_absensi_suma
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: absensi_suma
      MYSQL_USER: rian
      MYSQL_PASSWORD: rian
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3308:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_absensi_suma
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  dbdata: